[project]
name = "milestonetracker"
description = "Unique voting contract for project 10"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.milestonetracker]
path = "contracts/milestonetracker.clar"

[repl.analysis]
passes = ["check_checker"]
